### ISSUE TITLE
Using >pascalCase strips all quotes and white space out of JSON document

### ISSUE THREAD

**Issue by GarethBro3n** [adamwalzer/string-converter#9] opened 2020-10-16 11:17 UTC
So running >pascalCase in VSCode on the following:

```
{
    "thing": {
        "property_a": 1,
        "property_b": "2",
        "property_c": "3eeee",
    }
}
```
Becomes:

`ThingPropertyA1PropertyB2PropertyC3Eeee`

**Comment by adamwalzer** [comment] 2021-02-12 04:10
Hey @GarethBro3n,

Sorry I didn't realize this issue sooner. That's being said this is actually intended functionality. If you want to pascalCase just particular parts of your code, this extension allows you to do so by highlighting just those portions and choosing pascalCase. You can multi-select, but everything you select will be pascalCased. Having this extension choose which of the highlighted parts to manipulate would likely break the existing functionality. This does sounds like a good feature, but would likely have to be implemented as a separate function or as a separate extension all together. Sorry for the inconvenience, but if you'd like to contribute this functionality, I'd be happy to review it.

I'm going to close this issue for now as Won't Fix (Working As Intended).

Thanks,
Adam

**Closed as completed by adamwalzer** 2021-02-12 04:10 UTC

**Comment by GarethBro3n** [comment] 2021-02-12 10:46
Understood. I wonder if you could allow for a regex parameter to limit string matches that the function should run on, or treat non alphanumeric, -, _ chars etc as delimiters. But I accept that's not how you may have intended this extension to work. Good work anyway!

**Comment by adamwalzer** [comment] 2021-02-12 14:10
Good point. It would definitely be possible to take in a regexp string and match based on that and then only convert those matches. I would probably want to add tests to make sure we don't break existing functionality, but that is absolutely a possibility. I haven't looked at this code in quite a while, but I'll give it a look. Thanks!
